### PR TITLE
Fixes #3 : Linkified the links and wraped the text. 

### LINKED ISSUE #3: Linkify links
Please linkify links and make them shorter in the display - no need to show full length.

screenshot from 2016-07-18 14 41 59

### PR DESCRIPTION
**Pull request by daminisatya**

### CODE REVIEW

**Comment by daminisatya** [comment]
Adding more details. On linkifying the link and shortening it.

**Comment by daminisatya** [comment]
selection_202

**Comment by shivenmian** [comment]
+1

**Comment by daminisatya** [comment]
@mariobehling Please review.

**Comment by mariobehling** [comment]
Make link "Here is a map" into link, please.

**Comment by sudheesh001** [comment]
@daminisatya I don't see why this has to be closed, I think we need to discuss on this https://github.com/loklak/asksusi_com/issues/7 about this PR, this PR looks great and is near complete.

**Comment by daminisatya** [comment]
closing this wrt #7 
Thanks @sudheesh001 for the suggestion.

**Comment by sudheesh001** [comment]
Please discuss this before closing it. @mariobehling Feedback needed on #7

**Comment by daminisatya** [comment]
@mariobehling 
```Make link "Here is a map" into link, please.```
This is a generic linkification so there are links from coming from many rules, So IMO keeping this generic would not regress further bugs.

**Comment by daminisatya** [comment]
In favor of other conflicted discussions closing this to resolve the issues.

**Pull request merged**
